### PR TITLE
Fail to construct preload hamt shards when traversal fails

### LINKED ISSUE #54: HAMT Preloader does not return error even if blocks do not load
The HAMT Preloader ADL is meant to load all the blocks in the HAMT without following any links in the map's values.

Unfortunately, the way it does the preloading is by calling https://github.com/ipfs/go-unixfsnode/blob/364a5496925b291900d67c35b8b898e1a30b7f0a/hamt/shardeddir.go#L68-L71

While this would be fine if in fact -1 was returned during an error loading the HAMT. 

However, it does not because the contract for that function for this function is that `-1` is only returned if the node is not a list or a map and we know it is. https://github.com/ipld/go-ipld-prime/blob/65bfa53512f2328d19273e471ce4fd6d964055a2/datamodel/node.go#L131-L133

This means that when we have trouble loading a block we just continue on as if nothing happened which does not fulfill the contract of the preloader function

https://github.com/ipfs/go-unixfsnode/blob/364a5496925b291900d67c35b8b898e1a30b7f0a/hamt/shardeddir.go#L280-L283

---

This seems most readily resolvable by just using a different code path than `Length()` for doing the enumeration. Two that come to mind are:
1. Copying/reusing the Length code but where we return errors
2. Going through a map iterator that doesn't load the map value nodes

### PR DESCRIPTION
**Pull request by willscott**
Fix #54

### CODE REVIEW

**Review by rvagg — APPROVED** [review]

File: hamt/shardeddir.go [hunk 1]
```diff
@@ -272,20 +275,34 @@ func (n UnixFSHAMTShard) Length() int64 {
...
-	return total
+	return total, nil
+}
+
+// Length returns the length of a list, or the number of entries in a map,
+// or -1 if the node is not of list nor map kind.
+func (n UnixFSHAMTShard) Length() int64 {
+	len, err := n.length()
+	if err != nil {
+		return 0
```
Comment (aschmahmann) [inline hamt/shardeddir.go:303]: Don't feel strongly about the number chosen here, as mentioned in https://github.com/ipld/go-ipld-prime/issues/531 we're really in a rough spot here.

This is a behavior change from previously, but if you don't want to return `-1` or a different negative number then `0` is probably more reasonable than what we were doing here before.

Comment (willscott) [reply hamt/shardeddir.go:303]: i'm happy to take suggestions - do you think it makes sense to do `-2` or similar in this case?

Comment (rvagg) [reply hamt/shardeddir.go:303]: I'd prefer `0` until we have some kind of agreement on the best way to deal with https://github.com/ipld/go-ipld-prime/issues/531, otherwise this is an outlier.

**Comment by rvagg** [comment]
We could memoize the `err` inside `UnixFSHAMTShard` so the next call to a method that returns an error can return it. Unfortunately, by saying `0` to the `Length()` call we're minimising the chance that another method is going to be called on it.

**Comment by willscott** [comment]
given that 0 length leaves us unlikely to get the memoized error, i think i'm going to not add the complexity for that.
